### ISSUE TITLE
No support for OTP

### ISSUE THREAD

**Issue by ltworf** [CMB/cligh#17]
I tried using this but…

```
$ cligh configure
Username: aaaaa
Password:
Traceback (most recent call last):
  File "/usr/bin/cligh", line 45, in <module>
    main()
  File "/usr/bin/cligh", line 37, in main
    config.do_configcmd()
  File "/usr/lib/python3/dist-packages/cligh/config.py", line 78, in do_configcmd
    authorization = user.create_authorization(scopes=['user', 'repo', 'gist', 'delete_repo'], note='cligh',
  File "/usr/lib/python3/dist-packages/github/AuthenticatedUser.py", line 464, in create_authorization
    headers, data = self._requester.requestJsonAndCheck(
  File "/usr/lib/python3/dist-packages/github/Requester.py", line 275, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, self.__customConnection(url)))
  File "/usr/lib/python3/dist-packages/github/Requester.py", line 286, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.GithubException: 401 {'message': 'Must specify two-factor authentication OTP code.', 'documentation_url': 'https://developer.github.com/v3/auth#working-with-two-factor-authentication'}
```

This is because I have 2 factor authentication enabled on my account.

**Comment by eamanu** [comment]
This projects seems to be in the end of the life.  https://github.com/CMB/cligh/issues/16
@CMB  Could you confirm it, please?

**Comment by CMB** [comment]
Sorry I didn't notice this until now.  Yes cligh is end of life.  There
are more client options nowadays, and personally I'm more interested in
self-hostable repository setups and wanting to move off of github as much as
I can.
