### ISSUE TITLE
allow non-interactive repo create

### ISSUE THREAD

**Issue by yarikoptic** [CMB/cligh#7]
looks like project has stalled -- nevertheless

now it seems require user interaction where I hope there was a way to specify in cmdline, e..g for repo create:
```
$> cligh repo create datalad/testrepo--flavor--kind 
usage: cligh [-h] {configure,collab,issue,repo} ...
cligh: error: unrecognized arguments: datalad/testrepo--flavor--kind

$> cligh repo create                               
Repository name: ^CTraceback (most recent call last):
  File "/usr/bin/cligh", line 34, in <module>
    main()
  File "/usr/bin/cligh", line 31, in main
    args.func(client, args)
  File "/usr/lib/python2.7/dist-packages/cligh/repos.py", line 32, in create
    name = read_user_input('Repository name', validate_name)
  File "/usr/lib/python2.7/dist-packages/cligh/utils.py", line 33, in read_user_input
    user_text = sys.stdin.readline()
KeyboardInterrupt

```

**Comment by CMB** [comment]
Yaroslav Halchenko <notifications@github.com> writes:

> looks like project has stalled

Not necessarily stalled.  I'm willing to add more; just haven't had the
need / desire to do it.  I use the hub tool to fill in the gaps.

> now it seems require user interaction where I hope there was a way to
> specify in cmdline, e..g for repo create:

That shouldn't be too hard to fix.
When I wrote this code a few years ago, I basically wrote it for a
friend and me.  We're both blind, and I'm not too fond of the website.
So I wrote the simplest thing I possibly could, while trying to have the
code be user friendly for a blind person at the console.  So that's how
we end up with the user interaction.

**Comment by yarikoptic** [comment]
Yeah -- I have swallowed the pill now and installed  hub  as well even though it is not shipped with Debian yet.  So there is no rush really for this feature ;-)  Cheers and thanks!
